### ISSUE TITLE
A couple things/bugs I noticed

### ISSUE THREAD

**Issue by lgowen22** [Nibaru/More-Slabs-Stairs-and-Walls#1]
Bugs:
1: Warped and Crimson Log Walls are missing
2: All log/stem slabs, stairs, and walls are instamineable with a bare hand
3: Mud slabs, stairs, and walls don't sink the player a pixel or two like mud block does
4: Landing on a slime block wall doesn't bounce the player

5: This one is a bit different and maybe not fixable, but with Slabs Refabricated, all transparent/semitransparent slabs render improperly when combined with another slab. This is probably a problem for Slabs Refabricated to fix.

Other:
I think log stairs/slabs/walls should be strippable. I think it fits considering dirt slabs/stairs/walls can grow into grass variants. Similarly, it would be cool if you could turn dirt-style slabs/stairs/walls into path variants with a shovel.

**Comment by Nibaru** [comment]
Thanks for pointing these issues out. Ill get them fixed soon once I have the forge version updated. 

Having logs strippable and dirt paths would be great ill add that to the todo list.
