### ISSUE TITLE
Graphic bug for grass type + honey/slime slabs

### ISSUE THREAD

**Issue by Kierecko** [Nibaru/More-Slabs-Stairs-and-Walls#11]
When placing lower honey, slime, grass, podzol, mycelium, warped nylium or crimson nylium slabs underneath a full block or slab, the texture on the top side vanishes.
![mssw issue](https://user-images.githubusercontent.com/100862388/226691568-bd428f1e-a2a6-4175-8cea-c0df0cd21b1b.png)

Also on a different note but since this is only my second Issue I open in github idk if I should open a seperate one:
(Unstripped) Log walls, log stairs and log slabs can be insta-broken by hand.

We're playing on a server with mssw-1.19.2-2.2.0

**Comment by Nibaru** [comment]
Both of these issues were actually fixed in version 2.3.0

**Comment by Kierecko** [comment]
I do honestly not know how we didn't see that. Thanks a lot!
