### ISSUE TITLE
No Crying Obsidian slabs/stairs/walls (3.0)

### ISSUE THREAD

**Issue by Baesir** [Nibaru/More-Slabs-Stairs-and-Walls#26]
Everything else seems present except these blocks when searching through creative inventory

Edit: Version 3.0 for Fabric 1.20.1

![2023-09-06_01 01 18](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/assets/124665985/c2551ec6-f5cb-48a9-86a1-f0fa5fff5491)

**Comment by Zynara** [comment]
![image](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/assets/143786622/f43972e6-dc59-4805-9b34-f75e6fa55d07)
![image](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/assets/143786622/a555f609-815b-4902-9185-436860f0816a)
![image](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/assets/143786622/e6c35054-9bd1-4f1a-a6a0-49aae714a6b6)



It's there. I see it. I can craft it in the stone cutter AND crafting table.

**Comment by Baesir** [comment]
> ![image](https://user-images.githubusercontent.com/143786622/266111772-f43972e6-dc59-4805-9b34-f75e6fa55d07.png) ![image](https://user-images.githubusercontent.com/143786622/266111907-a555f609-815b-4902-9185-436860f0816a.png) ![image](https://user-images.githubusercontent.com/143786622/266112156-e6c35054-9bd1-4f1a-a6a0-49aae714a6b6.png)
> 
> It's there. I see it. I can craft it in the stone cutter AND crafting table.

In my screenshot you can see it doesn't pop up, do you have any suggestions?

**Comment by Baesir** [comment]
I've also looked at my log file and when the mod initializes crying obsidian is not present
[latest.log](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/files/12554430/latest.log)

Edit: unzipped the jar and found no instance of crying obsidian anywhere in assets or any other folders
Edit 2: unzipped the previous version (2.4.0) and it contains the crying obsidian assets, it seems they are just missing from 3.0

**Comment by Zynara** [comment]
Sorry, I don't have an answer then. I'm using 1.19.2.

**Comment by Baesir** [comment]
> Sorry, I don't have an answer then. I'm using 1.19.2.

It's okay! Your reply led me to check out the older versions of the mod to confirm that crying obsidian was indeed once there but somehow absent in the latest release
