### ISSUE TITLE
Crash on Forge 1.19.2 dedicated server

### ISSUE THREAD

**Issue by seancrain** [Nibaru/More-Slabs-Stairs-and-Walls#3]
It seems that the server is attempting to load a client-side line in the mod:

Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/color/block/BlockColors for invalid dist DEDICATED_SERVER

Version 2.2.0 for Forge 1.19.2 is in question

**Comment by Nibaru** [comment]
Thanks for pointing this out. I've published a fix on [Curseforge ](https://www.curseforge.com/minecraft/mc-mods/more-slabs-stairs-and-walls/files/4329366) and [Modrinth](https://modrinth.com/mod/moressw/version/2.2.0)
