### ISSUE TITLE
Wood Plank Wall Recipe Overrides Trapdoor Recipe

### ISSUE THREAD

**Issue by Casually-Anonymous** [Nibaru/More-Slabs-Stairs-and-Walls#36]
Every time I try to make a trapdoor, walls are the result instead. I haven't seen anything online even mentioning this, and I can't seem to be able to configure the mod to allow trapdoors. Anyone else have this issue & know how to fix it, or is just one of those things I'd have to disable the mod for?
[Minecraft Fabric 1.20.1, updated to most current version]
![image_2024-01-23_174807240](https://github.com/Nibaru/More-Slabs-Stairs-and-Walls/assets/153032710/3070a193-21c5-4cb3-a61a-1b4bfc50ab8a)

**Comment by Nibaru** [comment]
My apologies, I must have forgotten to change the plank recipes from default in the latest rewrite. I'll work on getting a update out to fix that tonight.

**Comment by autoteelar** [comment]
still having this same issue @Nibaru
