### ISSUE TITLE
leaf stairs turn into dirt blocks after while.

### ISSUE THREAD

**Issue by JannekeJairia** [Nibaru/More-Slabs-Stairs-and-Walls#4]
Hey! Great mod, love the options. 

I was playing with the leaves yesterday and when I came back several of the leaf stairs had turned into dirt. I didn't use slabs, so I don't know if they have the same issue. 
I think I used oak or dark oak leaf stairs. 
I retested it later on and the same happened. 

If it is useful information: the stairs were upside down

**Comment by Nibaru** [comment]
Well that is strange, Ill look into it. Are you running Forge or Fabric?

**Comment by JannekeJairia** [comment]
I'm running fabric
